# SuperSeatBoi
# created by jaylawl
#
# Donate: http://paypal.me/langejulian
# SpigotMC: https://www.spigotmc.org/resources/superseatboi.77321/
# Github-page: https://github.com/jaylawl/SuperSeatBoi
#
# There are no in-game commands except for "/superseatboi [reload]"
# This plugin does not require any permissions
#

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Settings:
  # Materials listed in "SeatBlock" & "ControlBlocks" must be valid Bukkit material enum
  # Those can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  SeatBlocks: []
  ControlBlocks:
    - REDSTONE_BLOCK
  # Whether to bother checking for a control block or not
  RequireControlBlock: true
  AllowSeatingWhileFalling: true
  AllowWaterloggedSeats: false
  AllowSeatingWhileSneaking: false
  AllowCreativeModeSeating: true
  BlacklistedWorlds: []

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~