main: de.jaylawl.superseatboi.SuperSeatBoi
name: SuperSeatBoi
version: "1.4.0"
api-version: "1.21.3"
author: jaylawl
website: https://github.com/jaylawl/SuperSeatBoi

depend: [ ]
softdepend: [ ]
loadbefore: [ ]

commands:

  superseatboi:
    aliases: [ ssb ]
    permission: "superseatboi.admin"
    permission-message: "§cInsufficient permission"

permissions: { }